# -*- coding: utf-8 -*-
"""07-Seaborn Exercises.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1NUVn4hEca6MjsbNFpBzpiF1Wa4eM7GvL

___

<a href='http://www.pieriandata.com'> <img src='../Pierian_Data_Logo.png' /></a>
___
# Seaborn Exercises

Time to practice your new seaborn skills! Try to recreate the plots below (don't worry about color schemes, just the plot itself.

## The Data

We will be working with a famous titanic data set for these exercises. Later on in the Machine Learning section of the course, we will revisit this data, and use it to predict survival rates of passengers. For now, we'll just focus on the visualization of the data with seaborn:
"""

# Commented out IPython magic to ensure Python compatibility.
import seaborn as sns
import matplotlib.pyplot as plt
# %matplotlib inline

sns.set_style('whitegrid')

titanic = sns.load_dataset('titanic')

titanic.head()

"""# Exercises

** Recreate the plots below using the titanic dataframe. There are very few hints since most of the plots can be done with just one or two lines of code and a hint would basically give away the solution. Keep careful attention to the x and y labels for hints.**

** *Note! In order to not lose the plot image, make sure you don't code in the cell that is directly above the plot, there is an extra cell above that one which won't overwrite that plot!* **
"""

sns.jointplot(x='fare',y='age',data=titanic)



sns.distplot(titanic['fare'],kde=False,color='r',bins=30)



sns.boxplot(x='class',y='age',data=titanic)



sns.swarmplot(x='class',y='age',data=titanic)



sns.countplot(titanic['sex'])



t = titanic.corr()
sns.heatmap(t,cmap='coolwarm')
plt.title('titanic.corr()')



g = sns.FacetGrid(data=titanic,col='sex')
g.map(plt.hist,'age')



"""# Great Job!

### That is it for now! We'll see a lot more of seaborn practice problems in the machine learning section!
"""