# -*- coding: utf-8 -*-
"""Categorical Plots.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_fGWDh_5G0vCmleig4gMGt48IGPbfbPG
"""

# Commented out IPython magic to ensure Python compatibility.
import seaborn as sns
# %matplotlib inline
tips = sns.load_dataset('tips')
tips.head()

import numpy as np

#Bar Plot
sns.barplot(x='sex',y='total_bill',data=tips)
#by default it represents average

sns.barplot(x='sex',y='total_bill',data=tips,estimator=np.std)

#Count Plot
sns.countplot(x='sex',data=tips)

sns.boxplot(x='day',y='total_bill',data=tips)

sns.boxplot(x='day',y='total_bill',data=tips,hue='smoker')

sns.violinplot(x='day',y='total_bill',data=tips)

sns.violinplot(x='day',y='total_bill',data=tips,hue='sex')

sns.violinplot(x='day',y='total_bill',data=tips,hue='sex',split=True)

sns.stripplot(x='day',y='total_bill',data=tips)

sns.stripplot(x='day',y='total_bill',data=tips,hue='sex',split=True)

sns.swarmplot(x='day',y='total_bill',data=tips)
#violin + stripplot

sns.factorplot(x='day',y='total_bill',data=tips,kind='bar')

sns.factorplot(x='day',y='total_bill',data=tips,kind='violin')

