# -*- coding: utf-8 -*-
"""Grids.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1a51Vxruu1TGDTxp7hiaogQbs6M_hrma4
"""

# Commented out IPython magic to ensure Python compatibility.
import seaborn as sns
# %matplotlib inline
iris = sns.load_dataset('iris')
iris.head()

sns.pairplot(iris)

g = sns.PairGrid(iris)
g

g = sns.PairGrid(iris)
g.map(plt.scatter)

g = sns.PairGrid(iris)
g.map_diag(sns.distplot)
g.map_upper(plt.scatter)
g.map_lower(sns.kdeplot)

tips = sns.load_dataset('tips')

g = sns.FacetGrid(data=tips,col='time',row='smoker')
g.map(sns.distplot,'total_bill')