# -*- coding: utf-8 -*-
"""Matrix plots.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1MBVwNh4rXfYP5VqZPsWK5hdONBofMJFC
"""

# Commented out IPython magic to ensure Python compatibility.
import seaborn as sns
# %matplotlib inline
tips = sns.load_dataset('tips')
flights = sns.load_dataset('flights')
tips.head()

flights.head()

tc = tips.corr()
tc

sns.heatmap(tc)

sns.heatmap(tc,annot=True,cmap='coolwarm')

flights

fp = flights.pivot_table(index = 'month',columns='year',values='passengers')
fp

sns.heatmap(fp)

sns.heatmap(fp,linecolor='white',linewidth=3)

sns.clustermap(fp)

sns.clustermap(fp,cmap='coolwarm',standard_scale=1)