# -*- coding: utf-8 -*-
"""Style and color.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/162qhhYp_TBbh3cRnlXncQVbjir5BjtXg
"""

# Commented out IPython magic to ensure Python compatibility.
import seaborn as sns
# %matplotlib inline
import matplotlib.pyplot as plt
tips = sns.load_dataset('tips')

sns.set_style('white')
sns.countplot(x = 'sex',data =tips)

sns.set_style('ticks')
sns.countplot(x = 'sex',data =tips)

sns.set_style('dark')
sns.countplot(x = 'sex',data =tips)

sns.set_style('whitegrid')
sns.countplot(x = 'sex',data =tips)

plt.figure(figsize=(12,3))
sns.countplot(x = 'sex',data =tips)

sns.set_context('poster',font_scale=2)
sns.countplot(x = 'sex',data =tips)

sns.set_context('notebook',font_scale=1)
sns.lmplot(x='total_bill',y='tip',data=tips,hue='sex',palette='seismic')